# Generated by Django 3.2 on 2021-04-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=150)),
                ('Pwd', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
            ],
        ),
    ]
