# Generated by Django 3.2 on 2021-04-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movieid', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Userid', models.CharField(max_length=200)),
                ('rating', models.IntegerField(max_length=200)),
            ],
        ),
    ]
