# Generated by Django 3.2 on 2021-04-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_data_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_movies',
            name='movieId',
            field=models.CharField(max_length=200),
        ),
    ]
