# Generated by Django 3.2 on 2021-04-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_data_movies_movieid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Movieratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=200)),
                ('movieindex', models.IntegerField()),
                ('userratings', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_movieratings', to='App.user')),
            ],
        ),
    ]
